name: Build and Deploy CI/CD 
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Sonarcloud-Analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      - name: Push Docker image to Docker Hub
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ secrets.APPLICATION }} . \
            --namespace ${{ secrets.NAMESPACE }} \
            --atomic 5m
      - name: Test service URLs
        run: |
           minikube service list
           minikube service nodejs-world --url

